# Use official Node.js 20 image as the base image
FROM node:20

# Set the working directory inside the container to /app
WORKDIR /app

# Copy all files from the current directory to the working directory in the container
COPY . .

# Expose port 3000 to allow external access
EXPOSE 3000