"""Created webpush subscription model

Revision ID: 6ddc8befc2df
Revises: f5e32ce62c76
Create Date: 2025-07-17 18:12:10.838806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ddc8befc2df'
down_revision: Union[str, None] = 'f5e32ce62c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webpush_subscription',
    sa.Column('id', sa.String(length=36), nullable=False, comment='訂閱 ID'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='使用者 ID'),
    sa.Column('endpoint', sa.Text(), nullable=False, comment='訂閱的 Endpoint'),
    sa.Column('keys', sa.JSON(), nullable=False, comment='訂閱的 Keys'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否有效'),
    sa.Column('user_agent', sa.String(length=255), nullable=False, comment='使用者代理'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='建立時間'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新時間'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webpush_subscription')
    # ### end Alembic commands ###
