"""Created modbus controller and point model

Revision ID: bdcd213614f1
Revises: 6ddc8befc2df
Create Date: 2025-07-22 10:40:46.618967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdcd213614f1'
down_revision: Union[str, None] = '6ddc8befc2df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modbus_controller',
    sa.Column('id', sa.String(length=36), nullable=False, comment='控制器 ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='控制器名稱'),
    sa.Column('host', sa.String(length=64), nullable=False, comment='TCP 主機位址'),
    sa.Column('port', sa.Integer(), nullable=False, comment='TCP 連接埠'),
    sa.Column('timeout', sa.Integer(), nullable=False, comment='逾時秒數'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='連線狀態 (True=已連線, False=未連線)'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='建立時間'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新時間'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modbus_point',
    sa.Column('id', sa.String(length=36), nullable=False, comment='點位 ID'),
    sa.Column('controller_id', sa.String(length=36), nullable=False, comment='控制器 ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='點位名稱'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='點位型態 (coil/input/holding_register/input_register)'),
    sa.Column('data_type', sa.String(length=50), nullable=False, comment='資料型態 (bool/int/float)'),
    sa.Column('address', sa.Integer(), nullable=False, comment='Modbus 位址'),
    sa.Column('len', sa.Integer(), nullable=False, comment='長度'),
    sa.Column('unit_id', sa.Integer(), nullable=False, comment='裝置 ID'),
    sa.Column('formula', sa.Text(), nullable=True, comment='轉換公式'),
    sa.Column('unit', sa.String(length=32), nullable=True, comment='單位'),
    sa.Column('min_value', sa.Float(), nullable=True, comment='最小值'),
    sa.Column('max_value', sa.Float(), nullable=True, comment='最大值'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='建立時間'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新時間'),
    sa.ForeignKeyConstraint(['controller_id'], ['modbus_controller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modbus_point')
    op.drop_table('modbus_controller')
    # ### end Alembic commands ###
