"""Created websocket events model

Revision ID: f5e32ce62c76
Revises: 
Create Date: 2025-07-17 18:10:04.143432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5e32ce62c76'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('websocket_events',
    sa.Column('id', sa.String(length=36), nullable=False, comment='事件 ID'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='使用者 ID'),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='事件類型'),
    sa.Column('event_time', sa.TIMESTAMP(), nullable=False, comment='事件時間'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='連線 IP'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='建立時間'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新時間'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('websocket_events')
    # ### end Alembic commands ###
